spring:
  profiles:
    active: dev # Activa el perfil de desarrollo
  application:
    name: BidMaster
  # Configuración R2DBC para PostgreSQL
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bidmaster
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
  # Configuración para Flyway (migraciones de base de datos)
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/bidmaster
    user: postgres
    password: postgres
    baseline-on-migrate: true
    clean-disabled: false     # Permite la limpieza de la base de datos
    validate-on-migrate: true # Valida las migraciones antes de aplicarlas
    locations: classpath:db/migration # Ubicación de los scripts de migración

  sql:
    init:
      mode: always

# Configuración de logging
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
    io:
      r2dbc:
        postgresql: DEBUG
    dev:
      mostapha:
        bidmaster: DEBUG

server:
  port: 8080